version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: clothing_db_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: clothing_db
    ports:
      - "33071:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
