<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Admin Dashboard - What is in your closet?</title>
  <link rel="stylesheet" href="${pageContext.request.contextPath}/static/css/common.css">
  <link rel="stylesheet" href="${pageContext.request.contextPath}/static/css/admin_dashboard.css">
</head>
<body>

  <%@ include file="includes/header.jsp" %>

  <main>
  <div class="matrix-container">

    <!-- Header Bar -->
    <div class="header-bar">
      <h1>🎨 จัดการสีมงคล </h1>

      <div class="controls">
        <div class="control-group">
          <label>ปี:</label>
          <select class="year-selector" id="year-select">
            <c:forEach var="year" begin="2020" end="2030">
              <option value="${year}" ${year == currentYear ? 'selected' : ''}>ปี ${year + 543}</option>
            </c:forEach>
          </select>
        </div>

        <div class="control-group">
          <label>แม่หมอ:</label>
          <select class="astrologer-selector" id="astrologer-select">
            <option value="">-- เลือกแม่หมอ --</option>
            <c:forEach var="a" items="${astrologers}">
              <option value="${a.astrologerName}" data-id="${a.astrologerId}">${a.astrologerName}</option>
            </c:forEach>
            <option value="__new__">+ เพิ่มแม่หมอใหม่</option>
          </select>
          <div class="new-astrologer-container" id="new-astrologer-container">
            <input type="text" class="new-astrologer-input" id="new-astrologer-input" placeholder="กรอกชื่อแม่หมอใหม่">
            <button class="btn-add-astrologer" id="btn-add-astrologer-inline" onclick="createNewAstrologer()" disabled>
              <span class="btn-icon">✨</span>
              <span class="btn-text">เพิ่มแม่หมอ</span>
            </button>
          </div>
        </div>

        <div style="display: flex; gap: 10px; margin-left: auto;">
          <button class="delete-astrologer-btn" id="delete-astrologer-btn" style="display: none;" onclick="deleteCurrentAstrologer()">ลบแม่หมอ</button>
          <button class="clear-form-btn" id="clear-form-btn" style="display: none;" onclick="clearForm()">ล้างฟอร์ม</button>
          <button class="submit-all-btn" id="submit-all-btn" disabled onclick="submitAll()">บันทึกทั้งหมด</button>
        </div>
      </div>

      <!-- Lucky Type Selection -->
      <div class="type-selection-container" id="type-selection-container">
        <div class="type-selection-header">
          <span> เลือกด้านโชคลาภที่ต้องการเพิ่ม</span>
          <button class="select-all-types-btn" onclick="selectAllTypes()">✓ เลือกทั้งหมด</button>
        </div>
        <div class="type-checkboxes" id="type-checkboxes">
          <!-- Checkboxes will be generated by JavaScript -->
        </div>
      </div>
    </div>

    <!-- Matrix Table -->
    <div class="table-wrapper">
      <div class="info-text">
        <strong>วิธีใช้:</strong> เลือกแม่หมอและปี แล้วคลิกที่ช่องในตารางเพื่อเพิ่มสีมงคล (แต่ละช่องคือการผสมระหว่างวันและด้านโชคลาภ) เมื่อเพิ่มครบแล้วคลิก "บันทึกทั้งหมด" เพื่อบันทึกในครั้งเดียว
      </div>

      <div id="table-container">
        <div class="empty-state">
          <h3>เลือกแม่หมอเพื่อเริ่มต้น</h3>
          <p>กรุณาเลือกแม่หมอจากด้านบนเพื่อแสดงตาราง</p>
        </div>
      </div>
    </div>

  </div>

  <!-- Color Picker Modal -->
  <div class="color-modal" id="color-modal">
    <div class="color-modal-content">
      <div class="color-modal-header">
        <div>
          <h3>🎨 เลือกสีมงคล</h3>
          <div class="color-modal-info" id="modal-info">เลือกสีสำหรับ: <strong id="modal-cell-info"></strong></div>
          <div class="color-modal-warning" id="modal-warning" style="display: none; margin-top: 10px; padding: 10px; background: linear-gradient(135deg, #f3e5f5, #e1bee7); border: 2px solid #9c27b0; border-radius: 8px; color: #9c27b0; font-size: 0.9rem; font-weight: 600;"></div>
        </div>
        <button class="close-modal" onclick="closeColorModal()">×</button>
      </div>

      <div class="color-grid-modal" id="color-grid">
        <!-- Color cards will be dynamically generated by JavaScript with sorted order -->
      </div>

      <div class="modal-footer">
        <div class="selected-count">เลือกแล้ว: <span id="selected-count">0</span> สี</div>
        <div class="modal-buttons">
          <button class="btn-clear-all" onclick="clearAllColors()">ล้างทั้งหมด</button>
          <button class="btn-confirm-colors" onclick="confirmColors()">✓ ยืนยัน</button>
        </div>
      </div>
    </div>
  </div>

  <!-- Delete Confirmation Modal -->
  <div class="color-modal" id="delete-modal">
    <div class="color-modal-content" style="max-width: 450px;">
      <div class="color-modal-header">
        <h3>ยืนยันการลบแม่หมอ</h3>
        <button class="close-modal" onclick="closeDeleteModal()">×</button>
      </div>

      <div style="padding: 20px; text-align: center;">
        <p style="font-size: 1.1rem; margin-bottom: 10px; color: var(--text-dark); font-weight: 600;">
          คุณต้องการลบแม่หมอ "<span id="delete-astrologer-name" style="color: #f44336;"></span>" หรือไม่?
        </p>
        <p style="font-size: 0.95rem; color: var(--text-light); margin-bottom: 20px;">
          ข้อมูลสีมงคลทั้งหมดของแม่หมอนี้จะถูกลบด้วย
        </p>
      </div>

      <div class="modal-footer" style="border-top: 1px solid var(--border-color); padding-top: 15px;">
        <div class="modal-buttons" style="width: 100%; justify-content: center; gap: 15px;">
          <button class="btn-clear-all" onclick="closeDeleteModal()" style="background: var(--border-color); color: var(--text-dark);">ยกเลิก</button>
          <button class="btn-confirm-colors" onclick="confirmDeleteAstrologer()" style="background: #f44336;">ยืนยันการลบ</button>
        </div>
      </div>
    </div>
  </div>

  <!-- Confirmation Modal -->
  <div class="color-modal" id="confirm-modal">
    <div class="color-modal-content" style="max-width: 500px;">
      <div class="color-modal-header">
        <h3 id="confirm-modal-title">ยืนยันการดำเนินการ</h3>
        <button class="close-modal" onclick="closeConfirmModal()">×</button>
      </div>

      <div style="padding: 25px; text-align: center;">
        <p id="confirm-modal-message" style="font-size: 1.15rem; margin-bottom: 20px; color: var(--text-dark); font-weight: 600; line-height: 1.6;">
        </p>
        <p style="font-size: 0.9rem; color: #f44336; font-weight: 500; margin-top: 15px; padding: 10px; background: #ffebee; border-radius: 8px; border-left: 4px solid #f44336;">
          กรุณาตรวจสอบให้แน่ใจก่อนดำเนินการ
        </p>
      </div>

      <div class="modal-footer" style="border-top: 1px solid var(--border-color); padding-top: 15px;">
        <div class="modal-buttons" style="width: 100%; display: flex; justify-content: space-between; gap: 15px;">
          <button class="btn-back" onclick="closeConfirmModal()" style="background: #e0e0e0 !important; color: #424242 !important; font-size: 1rem; padding: 12px 25px; border: 2px solid #bdbdbd !important; border-radius: 12px; font-weight: 600; cursor: pointer; display: flex; align-items: center; gap: 8px; font-family: 'Prompt', sans-serif; transition: all 0.3s ease;">
            <span style="font-size: 1.2rem;">←</span> ย้อนกลับ
          </button>
          <button class="btn-confirm-colors" id="confirm-modal-btn" onclick="confirmModalAction()" style="font-size: 1rem; padding: 12px 25px;">
            ยืนยัน ✓
          </button>
        </div>
      </div>
    </div>
  </div>

  </main>

  <%@ include file="includes/footer.jsp" %>

  <script src="${pageContext.request.contextPath}/static/js/admin_dashboard.js"></script>
  <script>
    const dashboardData = {
      currentYear: ${currentYear},
      days: [
        <c:forEach var="d" items="${daysOfWeek}" varStatus="status">
          "${d}"${!status.last ? ',' : ''}
        </c:forEach>
      ],
      luckyTypes: [
        <c:forEach var="t" items="${luckyColorTypes}" varStatus="status">
          { id: ${t.luckyColorTypeId}, name: "${t.luckyColorTypeName}" }${!status.last ? ',' : ''}
        </c:forEach>
      ],
      allColors: [
        <c:forEach var="c" items="${colorCategories}" varStatus="status">
          { id: ${c.colorCategoryId}, name: "${c.colorCategoryName}", hex: "${c.colorCategoryHex}" }${!status.last ? ',' : ''}
        </c:forEach>
      ]
    };

    setContextPath('${pageContext.request.contextPath}');
    initializeData(dashboardData);
    document.addEventListener('DOMContentLoaded', function() {
      initEventListeners();
    });
  </script>

</body>
</html>
